### PR TITLE
Converted handlers from https://github.com/ethanaobrien/web-server-chrome

### PR DESCRIPTION
**Pull request by ethanaobrien**
@terreng 

Zip of compiled app: https://drive.google.com/file/d/1c3BZVqmaA9oRCpiduoGMs_d6ta6m3hAO/view?usp=sharing

Bugs may exist (I tested everything)
I know of few bugs, I am working on them. Nothing major.

To Do: console.log through window OR log to file (do something so that the user can see console logs, any suggestions?)

### CODE REVIEW

**Comment by terreng** [comment]
So this has all the features except for https and http2? Well done.

We can implement a custom log function that just writes to a log.txt file in the %userdata% folder.

**Comment by ethanaobrien** [comment]
@terreng That sounds awesome. I dont have skill in that area, would you mind doing so?

**Comment by terreng** [comment]
I should have more time this weekend to work on this.

**Comment by ethanaobrien** [comment]
@terreng I fixed the console commands in my latest commit

**Comment by terreng** [comment]
So all of the console output from the server shows up in the console for the window? Great!

I also noticed that you were working on implementing a Windows tray icon, which is something I've done before. I don't think we should have a tray icon unless we need to show the status of something. What would we use it for?

**Comment by ethanaobrien** [comment]
For when you have background turned on it would be an easy way to re-open the app and to heck that the app is still open. I plan to have a quit button when you right click the icon too.

**Comment by ethanaobrien** [comment]
Sorry, I meant to say to check that the app is still open

**Comment by terreng** [comment]
Don't delete package-lock.json

**Comment by ethanaobrien** [comment]
@terreng Sorry, I fixed it

**Comment by ethanaobrien** [comment]
@terreng In my latest commit, I added a new way to get network interfaces. It is more accurate (gets them all) Could you please use this new function

**Comment by terreng** [comment]
> Could you please use this new function

I see the new function. Please go ahead and use it.

**Comment by terreng** [comment]
Let's have all the web server logic be in its own file, WSC.js. We'll use index.js just to do app logic and communicate between the window and the server.

**Comment by terreng** [comment]
I will merge once you are done with the new IP function. Is there anything else to do in this PR?

**Comment by ethanaobrien** [comment]
The only things that need to be completed is the new IP function, as  you said, a minor bug I found (should take like 5 minutes to fix), I need to update an outdated description in the POST readme and the Ui. How are the new options in the Ui coming? I should be able to get everything done by the end of today!

**Comment by terreng** [comment]
> How are the new options in the Ui coming?

That's what I'll do next after merging this PR.

**Comment by ethanaobrien** [comment]
@terreng Very, very sorry. It took longer then expected. I found a very major bug that took FOREVER to fix (Turns out it was just an incompatibility with send) all fixed though!

This is ready to merge

**Comment by ethanaobrien** [comment]
@terreng There seems to be some problems with the tray discarding (Once the app is packaged)

You said that you've worked with trays, could you fix this?

**Comment by terreng** [comment]
> could you fix this?

I'll take a look, but it's not a priority right? I'm going to focus on adding the new options to the UI first.

**Comment by terreng** [comment]
@ethanaobrien I added you as a collaborator to this repository. Please don't ever commit directly to the main branch. Let's keep making separate branches and pull requests for everything so we can review the changes before merging.

**Comment by ethanaobrien** [comment]
Ok, thank you!

**Pull request merged**
