### PR TITLE
Replace 404 custom var with injecting path into html (#11)

### LINKED ISSUE #11: Replace 404 custom var with injecting path into html

### PR DESCRIPTION
**Pull request by ethanaobrien**
Resolves #11 and a bug I found
```
optCustom400usevar
optCustom401usevar
optCustom403usevar
optCustom404usevar

optCustom400usevarvar
optCustom401usevarvar
optCustom403usevarvar
optCustom404usevarvar
```

For example, if the user has the variable set to `PATH`, the server will replace all `{{PATH}}` with the request path

For another example, if the user has the variable set to `locationoflostuser`, the server will replace all `{{locationoflostuser}}` with the request path

This is ready to merge

### CODE REVIEW

**Comment by terreng** [comment]
- Let's just have one string for all the different error pages. We don't need a separate one for each.
- I used `{{PATH}}` as an example, but the user should be able to choose whatever string they want. So just use exactly what string they put, and don't add a `{{` `}}` to it.
- You need to escape the path (You can use the existing `htmlescape` function).
- The error still refers to a javascript variable, so make sure to update that.

**Comment by ethanaobrien** [comment]
@terreng Could you explain, I dont quite understand. I think we should add `{{` `}}` so that it only replaces the parts that the user wants it to replace

**Comment by terreng** [comment]
The user should be able to specify whatever string they want. For example, they could type `{{PATH}}`, `%error_path%`, or whatever else they want. The user is responsible for picking a string that will replace the part they want.

**Comment by ethanaobrien** [comment]
Ok, one setting for all variables, don't add {{ and }}. I am not familiar with the htmlescape function, could you tell me what it is and how to use it? So I still push the script to set the window variable containing the location? I won't have access to a computer until tomorrow.

**Comment by terreng** [comment]
Search for the `htmlescape` function which I put in one of the files. It takes characters like `<` and encodes them. This is just to make sure that the URL path is treated as text and not as HTML.

I don't see any reason to still add the JavaScript variable.

**Comment by ethanaobrien** [comment]
Ok, so it encodes the URL, I think I know what you're talking about (not encodeuricomponent) would this use client side JavaScript. The way I have it now would use no client side JavaScript

**Comment by terreng** [comment]
`encodeuricomponent` is for encoding things in URLs, and what I'm talking about is similar but for HTML.

Escape the HTML on the server side. No client side JavaScript is necessary.

For example, if the URL was `https://example.com/?a=1&b=2`, after html escaping it would become `https://example.com/?a=1&amp;b=2`. (In this case, `&` turned into `&amp;`) When this is displayed on the page, the browser will automatically turn `&amp;` back into `&` before displaying it.

**Comment by ethanaobrien** [comment]
Ok, I got that. So the user would have a string like ([{PATH)]} or something like that and it would replace all of the occurrences with the encoded path?

**Comment by terreng** [comment]
Yep. It's pretty much what you already have except remove the `{{` and html escape the path.

**Comment by ethanaobrien** [comment]
Okie, I'll do that tomorrow

**Comment by ethanaobrien** [comment]
@terreng All finished

**Review by terreng — APPROVED** [review]
Looks good 👍

**Pull request merged**
